server:
  port: 8080
  forward-headers-strategy: framework

spring:
  mvc:
    throw-exception-if-no-handler-found: true

  application:
    name: omi-backend

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@${ADB_TNS_ALIAS}?TNS_ADMIN=${TNS_ADMIN}
    username: ${ADB_APP_USER}
    password: ${ADB_APP_PASSWORD}

  flyway:
    enabled: false

app:
  cors:
    allowed-origin: ${FRONTEND_ORIGIN}

springdoc:
  api-docs:
    path: /api/v3/api-docs

  swagger-ui:
    path: /api/swagger-ui.html
